name: Deploy to LIVE

run-name: ${{ github.actor }} is deploying to LIVE...

on:
  release:
    types: [published]


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/strapi
            git pull origin main
            npm ci
            npm run build
            pm2 restart strapi